version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: flask run 
    stop_signal: SIGINT
    environment:
      DATABASE_URL: DATABASE_URL
      CELERY_BROKER_URL: CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: CELERY_RESULT_BACKEND
    restart: always
    volumes:
      - type: bind
        source: ./backend
        target: /app
    depends_on:
      - db
      - redis

  proxy:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports: 
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  celery-worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A app worker --loglevel=info
    environment:
      DATABASE_URL: DATABASE_URL
      CELERY_BROKER_URL: CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: CELERY_RESULT_BACKEND
    volumes:
      - type: bind
        source: ./backend
        target: /app
    depends_on:
      - db
      - redis