version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    stop_signal: SIGINT
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile

    ports:
      - "80:80"
    depends_on:
      - backend